/** Products Action Types */
/** FETCH ACTION TYPES START */
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

export const FETCH_PRODUCT = 'FETCH_PRODUCT';

export const FETCH_PRODUCT_CATEGORIES = 'FETCH_PRODUCT_CATEGORIES';
export const FETCH_PRODUCT_CATEGORIES_FAIL = 'FETCH_PRODUCT_CATEGORIES_FAIL';
export const FETCH_PRODUCT_CATEGORIES_SUCCESS =
	'FETCH_PRODUCT_CATEGORIES_SUCCESS';
/** FETCH ACTION TYPES END */

/** FILTERING & SORTING ACTION TYPES START */
export const CHECK_CATEGORY = 'CHECK_CATEGORY';
export const FILTER_BY_CATEGORIES = 'FILTER_BY_CATEGORIES';

export const SET_MIN_VALUE = 'SET_MIN_VALUE';
export const SET_MAX_VALUE = 'SET_MAX_VALUE';
export const FILTER_BY_PRICES = 'FILTER_BY_PRICES';

export const SELECT_OPTION = 'SELECT_OPTION';
export const SORT_BY_NAME = 'SORT_BY_NAME';
export const SORT_BY_PRICE = 'SORT_BY_PRICE';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';

export const SELECT_PRODUCT_ID = 'SELECT_PRODUCT_ID';
/** FILTERING AND SORTING ACTION TYPES END */

export const GET_RELATED_PRODUCTS = 'GET_RELATED_PRODUCTS';

export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';

/** Cart Action Types*/
export const SELECT_QUANTITY = 'SELECT_QUANTITY';
export const ADD_TO_CART = 'ADD_TO_CART';

/** Pagination Action Types */
export const LOAD_PAGES = 'LOAD_PAGES';
export const LOAD_PREVIOUS_PAGE = 'LOAD_PREVIOUS_PAGE';
export const LOAD_NEXT_PAGE = 'LOAD_NEXT_PAGE';
export const LOAD_SELECTED_PAGE = 'LOAD_SELECTED_PAGE';

export const SET_PAGE_SIZE = 'SET_PAGE_SIZE';
