/** Products Action Types */
/** FETCH ACTION TYPES START */
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

export const FETCH_PRODUCT = 'FETCH_PRODUCT';

export const FETCH_PRODUCT_CATEGORIES = 'FETCH_PRODUCT_CATEGORIES';
export const FETCH_PRODUCT_CATEGORIES_FAIL = 'FETCH_PRODUCT_CATEGORIES_FAIL';
export const FETCH_PRODUCT_CATEGORIES_SUCCESS =
	'FETCH_PRODUCT_CATEGORIES_SUCCESS';
/** FETCH ACTION TYPES END */

/** FILTERING & SORTING ACTION TYPES START */
export const CHECK_CATEGORY = 'CHECK_CATEGORY';
export const FILTER_BY_CATEGORIES = 'FILTER_BY_CATEGORIES';

export const SET_MIN_VALUE = 'SET_MIN_VALUE';
export const SET_MAX_VALUE = 'SET_MAX_VALUE';
export const FILTER_BY_PRICES = 'FILTER_BY_PRICES';

export const SELECT_OPTION = 'SELECT_OPTION';
export const SORT_BY_NAME = 'SORT_BY_NAME';
export const SORT_BY_PRICE = 'SORT_BY_PRICE';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';

export const SELECT_PRODUCT_ID = 'SELECT_PRODUCT_ID';
/** FILTERING AND SORTING ACTION TYPES END */

export const GET_RELATED_PRODUCTS = 'GET_RELATED_PRODUCTS';

export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';

/** Cart Action Types*/
export const SELECT_QUANTITY = 'SELECT_QUANTITY';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const SET_QUANTITY = 'SET_QUANTITY';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';

export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

/** Pagination Action Types */
export const LOAD_PAGES = 'LOAD_PAGES';
export const LOAD_PREVIOUS_PAGE = 'LOAD_PREVIOUS_PAGE';
export const LOAD_NEXT_PAGE = 'LOAD_NEXT_PAGE';
export const LOAD_SELECTED_PAGE = 'LOAD_SELECTED_PAGE';

export const SET_PAGE_SIZE = 'SET_PAGE_SIZE';

/** Authentication Action Types */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FAIL = 'LOGIN_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_SUCCESS';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_FAIL = 'REGISTER_FAIL';
export const REGISTER_USER_SUCCESS = 'REGISTER_SUCCESS';

export const SET_USER = 'SET_USER';

export const LOADING_TO_LOGIN = 'LOADING_TO_LOGIN';
export const LOADING_TO_REGISTER = 'LOADING_TO_REGISTER';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const LOADING_USERS = 'LOADING_USERS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGOUT_USER = 'LOGOUT_SUCCESS';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
